import "./globals.css";
import '@/assets/css/dropdownmenu.css'
import '@/assets/css/sidebar.css'
import "@/assets/css/progress.css"
import 'bootstrap/dist/css/bootstrap.css'

import NextTopLoader from "nextjs-toploader";
export const metadata = {
  title: "blog-web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
        {/* <NextTopLoader color="#ff661f" height={2} speed={500}/> */}
      </body>
    </html>
  );
}
